### ISSUE TITLE
`.map.js` files are not recognized

### ISSUE THREAD

**Issue by alekkowalczyk** [hbenl/vscode-mocha-test-adapter#55] opened 2019-06-13 12:12 UTC
I'm having following config in a TypeScript project:

```
        	"mochaExplorer.nodePath": null,
		"mochaExplorer.logpanel": true,
		"mochaExplorer.files": "dist/tests/**/*.js",
		"mochaExplorer.mochaPath": "node_modules/mocha",
```

I have set in the `tsconfig.json` - ` "outDir": "dist"` with source maps enabled.

The test explorer discovers the tests in the `dist` folder, but it looks like it doesn't use the `.map.js` files at all, for pointing to the test nor for debugging or adding context actions. 
Is it possible at all, or is `ts-node` the only option to make it work?

Tried also:

`"mochaExplorer.require": "source-map-support/register"`

which works when running mocha from console (showing proper call stacks with `ts` files), but the test explorer is still pointing to `js` files

**Comment by hbenl** [comment] 2019-06-13 17:09
Currently, `ts-node` is the only option. But using `source-map-support` sounds like a good idea (and should work in principle), I'll look into this.

**Comment by hbenl** [comment] 2019-06-14 16:10
Using `"mochaExplorer.require": "source-map-support/register"` to run transpiled sources is now supported in version 2.1.0, check it out and tell me if it works for you.

**Comment by alekkowalczyk** [comment] 2019-06-16 12:20
Works like a charm now, thanks for quick response, you made my work now way more straightforward by using the VSCode extension :)

**Comment by alekkowalczyk** [comment] 2019-06-16 12:27
After using a little bit - a small'ish bug - selecting "show source" on a test works perfectly, but when selected on a `describe` section - it navigates to the `.js` file instead the `.ts` file

**Comment by hbenl** [comment] 2019-06-17 17:22
I couldn't reproduce this - could you create an example project that shows this behaviour?

**Comment by alekkowalczyk** [comment] 2019-06-18 14:06
Will try to make an example project, but noticed it's the case on nested decribe, i.e.

```
describe("level 1", () => {
   describe("level 2", () => {
     describe("level 3", () => {
         it("test", () => {
                //...
         });
     });
   });
});
```

clicking on `test` and `level 3` goes to the correct place in TypeScript, but clicking `level 2`  or `level 1` points to `//# sourceMappingURL=....` in the `js` file

**Comment by hbenl** [comment] 2019-06-18 16:26
That example still worked for me... until I added `"mochaExplorer.nodePath": null` to my settings. With that setting I could reproduce the behaviour you described exactly.
I'll investigate this, but for now you should be able to make it work by removing that setting.

**Comment by hbenl** [comment] 2019-06-23 15:29
I fixed the location detection for nested `describe`s in version 2.1.2. You may also have noticed that error decorations didn't work with `source-map-support`, that is also fixed now.

**Closed by hbenl** 2019-06-23 15:29 UTC
