### ISSUE TITLE
Issue with custom file location for --config with mocha 6.0.0

### ISSUE THREAD

**Issue by AartiJ** [hbenl/vscode-mocha-test-adapter#38] opened 2019-03-01 16:50 UTC
I am trying to give custom location for the .mocharc.js file in my package.json for an npm command and Getting below Issue. Please help. 

My .mocharc.js file is in test folder under Project directory.
npm command as below
mocha --config test/.mocharc.js --opts ./node_modules/../../mocha.opts --reporter mocha-allure-reporter

Error: failed to parse test/.mocharc.js: Error: Cannot find module 'test/.mocharc.js'
    at exports.loadConfig.filepath (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/config.js:63:11)
    at loadRc (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:228:21)
    at loadOptions (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/options.js:298:20)
    at Object.exports.main (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/lib/cli/cli.js:62:18)
    at Object.<anonymous> (/Users/ajadeja/git_test/ace-ilp-lib/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Waiting for the debugger to disconnect...

Process finished with exit code 1

**Comment by hbenl** [comment] 2019-03-02 19:06
This adapter doesn't support the new configuration files introduced in Mocha 6 yet.
Closing this as a duplicate of #37.

**Closed by hbenl** 2019-03-02 19:06 UTC

**Comment by hbenl** [comment] 2019-03-26 20:49
I've just published version 1.7.0 which supports the new configuration files.
